# Generated by Django 5.2.4 on 2025-07-10 09:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registration_no', models.CharField(max_length=50, unique=True)),
                ('academic_year', models.CharField(max_length=20)),
                ('course', models.CharField(max_length=100)),
                ('year_of_study', models.CharField(max_length=20)),
                ('company_name', models.CharField(max_length=100)),
                ('company_address', models.TextField()),
                ('duration_in_weeks', models.IntegerField()),
                ('start_date', models.DateField()),
                ('completion_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'students',
            },
        ),
    ]
