# Generated by Django 5.2.4 on 2025-07-21 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_initial'),
        ('supervisors', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='company_address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='company_name',
        ),
        migrations.AddField(
            model_name='student',
            name='company',
            field=models.ForeignKey(default='a51f306b-8b67-4b8c-bcae-448a13fd0f47', on_delete=django.db.models.deletion.CASCADE, related_name='students', to='supervisors.company'),
            preserve_default=False,
        ),
    ]
