# Generated by Django 5.2.4 on 2025-07-29 06:25

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_student_company_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Task Categories',
                'db_table': 'task_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DailyTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
                ('tools_used', models.JSONField(blank=True, default=list)),
                ('skills_applied', models.JSONField(blank=True, default=list)),
                ('hours_spent', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(24)])),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('week_number', models.PositiveIntegerField(editable=False)),
                ('iso_year', models.PositiveIntegerField(editable=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_tasks', to='students.student')),
                ('task_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='students.taskcategory')),
            ],
            options={
                'db_table': 'daily_tasks',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['student', 'date'], name='daily_tasks_student_b8b285_idx'), models.Index(fields=['week_number', 'iso_year'], name='daily_tasks_week_nu_02ed12_idx')],
                'unique_together': {('student', 'date')},
            },
        ),
    ]
